name: Test Neovim Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testBranch
  pull_request:
    paths:
      - '**.lua'
      - 'lua/tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Neovim
        run: |
          sudo apt-get update && sudo apt-get install -y neovim

      - name: Install packer.nvim
        run: |
          git clone --depth 1 https://github.com/wbthomason/packer.nvim \
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim

      - name: Setup Neovim Config
        run: |
          mkdir -p ~/.config/nvim
          cat <<EOF > ~/.config/nvim/init.lua
          vim.cmd [[packadd packer.nvim]]
          require('packer').startup(function(use)
            use 'wbthomason/packer.nvim'
            use 'nvim-lua/plenary.nvim'
            use { '${{ github.workspace }}', as = 'neo-psql' }
          end)
          EOF

      - name: Run PackerSync
        run: |
          nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

      - name: Run Tests
        run: |
          nvim --headless -c "PlenaryBustedDirectory lua/tests/ { minimal_init = '${{ github.workspace }}/.config/nvim/init.lua' }" -c "qa"