name: Test Neovim Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testBranch
  pull_request:
    paths:
      - '**.lua'
      - 'lua/tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to latest version for better compatibility

      - name: Install Neovim
        run: |
          sudo apt-get update && sudo apt-get install -y neovim

      - name: Install packer.nvim
        run: |
          git clone --depth 1 https://github.com/wbthomason/packer.nvim \
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim

      - name: Setup Neovim Config
        run: |
          mkdir -p ~/.config/nvim
          cat <<EOF > ~/.config/nvim/init.lua
          vim.cmd [[packadd packer.nvim]]
          require('packer').startup(function(use)
            use 'wbthomason/packer.nvim'
            use 'nvim-lua/plenary.nvim'  -- Dependency for testing
            use { '${{ github.workspace }}', as = 'neo-psql' }  -- Use GitHub workspace for local plugin
          end)
          EOF

      - name: Run PackerSync
        run: |
          nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
        # Ensures PackerSync completes before proceeding

      - name: Debug Packer Installation
        run: |
          echo "Packer start directory:"
          ls -la ~/.local/share/nvim/site/pack/packer/start/
          echo "Neovim runtimepath:"
          nvim --headless -c 'lua print(vim.inspect(vim.api.nvim_list_runtime_paths()))' -c 'qa'

      - name: Verify plenary.nvim Availability
        run: |
          nvim --headless -c "lua print(vim.inspect(require('plenary')))" -c "qa" || { echo "Plenary not found"; exit 1; }
        # Fail the step if plenary isn’t loaded

      - name: Run Tests
        run: |
          nvim --headless -c "PlenaryBustedDirectory lua/tests/ { minimal_init = '${{ github.workspace }}/.config/nvim/init.lua' }" -c "qa"
        # Specify minimal_init to ensure the correct config is used