name: Test Neovim Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - testBranch
  pull_request:
    paths:
      - '**.lua'
      - 'lua/tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Neovim
        run: |
          sudo apt update && sudo apt install -y neovim

      - name: Install packer.nvim
        run: |
          git clone --depth 1 https://github.com/wbthomason/packer.nvim \
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      - name: Check if packer.nvim is installed
        run: |
          ls -la ~/.local/share/nvim/site/pack/packer/start/


      - name: Setup Neovim and Install Dependencies
        run: |
          mkdir -p ~/.config/nvim
          cat <<EOF > ~/.config/nvim/init.lua
          vim.cmd [[packadd packer.nvim]]
          require('packer').startup(function(use)
            use 'wbthomason/packer.nvim'
            use 'nvim-lua/plenary.nvim'  -- Needed for testing
            use { vim.fn.getcwd(), as = 'neo-psql' }
          end)
          EOF

      - name: Run PackerSync
        run: |
          nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' -c 'qa'
 
      - name: Check if plenary.nvim is installed
        run: |
          ls -la ~/.local/share/nvim/site/pack/packer/start/

      - name: Verify plenary.nvim in Neovim
        run: |
          nvim --headless -c "lua print(vim.inspect(require('plenary')))" -c "qa" || echo 'Plenary not found'

      - name: Run Tests
        run: |
          nvim --headless -c "PlenaryBustedDirectory lua/tests/ { minimal = true }" -c "qa"
